# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OkctlAT0_0_7 < Formula
  desc "Opinionated and effortless infrastructure and application management"
  homepage "https://github.com/oslokommune/okctl"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oslokommune/goreleaser-test/releases/download/v0.0.7/okctl_Darwin_amd64.tar.gz"
      sha256 "d32981a19e8abc18e5f1da8abc1c59669b00b7b8084f1200e782d044ade51757"

      def install
        bin.install "goreleaser-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/oslokommune/goreleaser-test/releases/download/v0.0.7/okctl_Linux_amd64.tar.gz"
      sha256 "6a7907c5238444f69942760dd40bb1fdb100df0053e80288332f450de2dfdb8b"

      def install
        bin.install "goreleaser-test"
      end
    end
  end

  head "https://github.com/oslokommune/goreleaser-test/releases/download/latest_release/goreleaser-test_Darwin_amd64.tar.gz"
end
