# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Okctl < Formula
  desc "Opinionated and effortless infrastructure and application management"
  homepage "https://github.com/oslokommune/okctl"
  version "0.0.74"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oslokommune/okctl/releases/download/v0.0.74/okctl_Darwin_amd64.tar.gz"
      sha256 "5d1fa22f7f7b33dba9699d9ecf6727fb6f6bc282ac960892004f877248bb819f"

      def install
        bin.install "okctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/oslokommune/okctl/releases/download/v0.0.74/okctl_Linux_amd64.tar.gz"
      sha256 "235cedf03e0c83ad9fed5fbb72a695321f91879e8fa7a9476347ad7405c4939d"

      def install
        bin.install "okctl"
      end
    end
  end

  head "https://github.com/oslokommune/okctl/releases/download/latest_release/okctl_Darwin_amd64.tar.gz"
end
