# This file was generated by GoReleaser. DO NOT EDIT.
class Okctl < Formula
  desc "Opinionated and effortless infrastructure and application management"
  homepage "https://github.com/oslokommune/okctl"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/oslokommune/okctl/releases/download/v0.0.2/okctl_Darwin_amd64.tar.gz"
    sha256 "13e5c395e58ed1054dbf6d054198309daf39297203fa5a4b56466e4da2947ce8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/oslokommune/okctl/releases/download/v0.0.2/okctl_Linux_amd64.tar.gz"
      sha256 "86748049bb9ffd2ac9744fdecc14f0e3a0932b02498ad1c60ab78020cbe9d6a4"
    end
  end
  
  head "https://github.com/oslokommune/okctl/releases/download/latest_release/okctl_Darwin_amd64.tar.gz"

  def install
    bin.install "okctl"
  end
end
